[general]
live_config_reload = false
ipc_socket = false

[window]
dynamic_padding = true
decorations = "none"
dynamic_title = false

[scrolling]
multiplier = 1

[font]
normal.family = "Hack Nerd Font"
size = 10

[colors]
[colors.primary]
foreground = "#ffffff"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0000ff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[cursor]
style.blinking = "Never"

[mouse]
hide_when_typing = true
